version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging into ECR
      - aws --version
      - REPOSITORY_URI=282865065290.dkr.ecr.us-east-1.amazonaws.com/cursoarquitectura02
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 282865065290.dkr.ecr.us-east-1.amazonaws.com
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - ENVIRONMENT=$(echo $environment)

  build:
    commands:
      - echo Build started on `date`
      - echo Building docker image
      - aws s3 cp s3://devops-arquitectura03/$ENVIRONMENT/.env .env
      - npm install
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing docker images
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG

artifacts:
  files:
    - 'Dockerrun.aws.json'
